### ISSUE TITLE
CTRL+Z does not work when there's a keyword group selected

### ISSUE THREAD

**Issue by michael** [substance/sourcedata-smartfigure-editor#19]
It only works with regular text selections. I have a feeling like this was already working. @oliver---- just to double check.

Using the undo/redo buttons from the menu works as expected.

**Comment by michael** [comment]
I think this is related to global key handling. This was working already. Keyboard shortcuts for deleting an author are also not working atm.

Reproduce: Select an author and use the "DELETE" key.

**Comment by oliver----** [comment]
Same problem as #32. Resolved.
