### ISSUE TITLE
MultiInput related improvements

### ISSUE THREAD

**Issue by michael** [substance/sourcedata-smartfigure-editor#20]
- use default size for keyword group editor (think it looks better)
- remove css and component for OptionalFieldsToggle
- when i change city name in affiliations editor it does not get updated
- when there is only one field in a MultiInput, don't show the trash icon

**Comment by Integral** [comment]
let's use 500px medium?
<img width="576" alt="Screen Shot 2019-12-13 at 22 27 41" src="https://user-images.githubusercontent.com/182010/70826377-d53e9f00-1df7-11ea-9ad4-f9f2c3077f8e.png">

**Comment by Integral** [comment]
@michael done

**Comment by michael** [comment]
If that's working, pls merge! It's looking good.
