### ISSUE TITLE
Apply styles for form rows (labels + values)

### ISSUE THREAD

**Issue by michael** [substance/sourcedata-smartfigure-editor#26]
![image](https://user-images.githubusercontent.com/2931/70899870-e0f8b400-1ff7-11ea-8256-64e8f6b61261.png)

For labels: Interface font (Fira Sans Medium)
For values (like affiliation rows in MultiSelect): Body font (Fira Sans regular)

**Comment by Integral** [comment]
@michael let's move this issue
there is a problem with multi select items style
in the mockup we are using 16px body text-style for them
but in sourcedata we have 18px body and it is too much for this case

**Comment by michael** [comment]
Yes I will take that over, needs more thinking and careful applying of rules.
