### ISSUE TITLE
Use real title in TOC

### ISSUE THREAD

**Issue by michael** [substance/sourcedata-smartfigure-editor#28]
![image](https://user-images.githubusercontent.com/2931/70921527-c1c44b80-2024-11ea-9032-52f896fc1f23.png)

We now show all title + headings in the TOC. To be consistent, instead of Title we want to see the actual title, so it matches with the document content.

@Integral can you render the doc title property there and use CSS ellipsis to cut off long titles. As shown in the screenshot.

**Comment by Integral** [comment]
This is ready, please review #35.
