### ISSUE TITLE
Fix CSS responsible for height of editor and content

### ISSUE THREAD

**Issue by oliver----** [substance/sourcedata-smartfigure-editor#31]
At the moment, there is always content at the very bottom, where you can not even scroll to.

![image](https://user-images.githubusercontent.com/284099/71149694-aed19700-222f-11ea-831f-2650ca6aa29d.png)

**Comment by oliver----** [comment]
This does not happen in electron build, where we have only the editor without the header.

**Comment by Integral** [comment]
This looks very strange to me. I can't reproduce it with default document and those section titles looks completely different in chrome, look:
![Screenshot 2019-12-19 at 15 51 31](https://user-images.githubusercontent.com/182010/71174970-6fc73400-2277-11ea-9fd6-beb64de0039c.png)

**Comment by oliver----** [comment]
I have moved to the same layout in the web demo, as in the app now. I.e. ditching SmartFigurePage.
Removing that extra layer of flex-layout solved the Safari problem, and revealed the source of the problem described here. There seems to be bug in Chrome, because despite of flex, it computes a too large height for the content when content has height 100%. Solution is to use calc() manually, i.e. 100- toolbar-height.
