### ISSUE TITLE
References & citations

### ISSUE THREAD

**Issue by michael** [substance/sourcedata-smartfigure-editor#33]
# References

![image](https://user-images.githubusercontent.com/2931/71174256-0e966500-2265-11ea-94cb-402f7159a3ae.png)

- "Create Reference" in SmartFigure menu
- Edit in place
- Delete Reference in contextual menu
- Automatically ordered depending on citation order.

# Citations

## Create

Opens as a popup, when confirmed, creates a labelled citation at the requested cursor position.

![image](https://user-images.githubusercontent.com/2931/71174480-98463280-2265-11ea-8279-76c1f2365223.png)

If desired reference has not been created yet, use an in-place dialog to ad-hoc create and cite a fresh reference.

![image](https://user-images.githubusercontent.com/2931/71174469-93817e80-2265-11ea-9e24-926a241224fb.png)

## Preview Citation

When you select a citation in the text either via click or via keyboard

![image](https://user-images.githubusercontent.com/2931/71174428-72209280-2265-11ea-9479-a3162c8c446f.png)

## Edit Citation

![image](https://user-images.githubusercontent.com/2931/71174452-85336280-2265-11ea-8cc4-161901620e12.png)

**Comment by oliver----** [comment]
Done.
