### ISSUE TITLE
Data files should be downloadable

### ISSUE THREAD

**Issue by source-data** [substance/sourcedata-smartfigure-editor#37]
It is now only possible to add,  insert, move and delete files in a SmartFigures. But it is not possible to download them. In terms of .smartfigure package, it means it is only possible to package files but not to extract them. 

Data files should be downloadable so that users who receive a package can easily extract the file from the package and use them. Download should be possible both from the panel adding a download action to the Attached File contextual menu and from the file list by adding a downlaod action from the File contextual menu.

![image](https://user-images.githubusercontent.com/23602/72428950-13303980-378f-11ea-9048-136768682ab0.png)

![image](https://user-images.githubusercontent.com/23602/72428845-d19f8e80-378e-11ea-8467-0116ef58887c.png)

**Comment by oliver----** [comment]
Instead of adding a download tool to each resource, I have added an option to export the whole DAR as ZIP file:
![image](https://user-images.githubusercontent.com/284099/75980764-6ac36980-5ee3-11ea-85c9-e806e8a7060e.png)
