### ISSUE TITLE
Popover didn't closed after annotation/inline-node deletion

### ISSUE THREAD

**Issue by Integral** [substance/sourcedata-smartfigure-editor#41]
E.g. if you put a cursor on link or citation and popover got opened and then you delete that citation or link, popover is still opened which is a bit strange (there was a citation instead of HI):
![Screenshot 2020-02-26 at 22 42 12](https://user-images.githubusercontent.com/182010/75381348-a65da280-58e9-11ea-8baa-c1af83ea88e4.png)

**Comment by oliver----** [comment]
Fixed.
